### PR TITLE
#95 - Write test for SVG elements to make sure they're polyfilled.

### LINKED ISSUE #95: SVG elements aren't polyfilled
Test to reproduce: 

``` js
describe('SVGElement', function () {
  it('should be polyfilled', function () {
    const div = document.createElement('div');
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    div.attachShadow({ mode: 'open' });
    div.shadowRoot.appendChild(document.createElement('slot'));
    div.appendChild(svg);
    expect(svg.parentNode).to.equal(div);
  });
});
```

We probably don't need to test all methods and properties like we do on `HTMLElement`, but we should ensure that the polyfilled methods on `SVGElement` equal the methods on `HTMLElement`.

### PR DESCRIPTION
**Pull request by treshugart**
They aren't polyfilled yet so this will fail the build. Subsequent commits will fix.

Fixes #95.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -838,9 +838,10 @@ const members = {
 };
 
 if (!('attachShadow' in document.createElement('div'))) {
+  const commProto = Comment.prototype;
```
Comment (treshugart) [inline src/index.js:841]: Reordered the `prototype` constants to be alpha ordered. Left the node instances alone for now.

**Comment by adevnadia** [comment]
lgtm

**Comment by bengummer** [comment]
lgtm
