### PR TITLE
#137 - Fix issue when document fragment is appended to another node and children aren't updated

### LINKED ISSUE #137: DocumentFragment appending doesn't update children
When you have a document fragment and append it to another node, the children of the document fragment still report that the `parentNode` is the fragment.

Test case:

```js
const frag = document.createDocumentFragment();
const ch1 = document.createElement('div');

frag.appendChild(ch1);
target.appendChild(frag);
expect(ch1.parentNode).to.equal(target);
```

### PR DESCRIPTION
**Pull request by treshugart**
Fixes #137.

### CODE REVIEW

File: src/v1/index.js [hunk 1]
```diff
@@ -422,10 +422,6 @@ function appendChildOrInsertBefore (host, newNode, refNode) {
   switch (nodeType) {
     case 'fragment':
     case 'node':
-      if (canPatchNativeAccessors) {
```
Comment (treshugart) [inline src/v1/index.js:425]: Just removing this fixed the issue. All other tests still pass. What was happening is that the `children` of the `DocumentFragment` weren't being updated after being moved. The `addNodeToNode` automatically does this using `registerNode`.

File: src/v1/index.js [hunk 2]
```diff
@@ -695,7 +691,6 @@ const members = {
   insertBefore: {
     value (newNode, refNode) {
       appendChildOrInsertBefore(this, newNode, refNode);
-
```
Comment (treshugart) [inline src/v1/index.js:698]: Boy scout: consistency with other code like this.

File: test/lib/create.js [hunk 3]
```diff
@@ -1,4 +1,4 @@
-export default (name, attrs = {}, chren = []) => {
+export default (name = 'div', attrs = {}, chren = []) => {
```
Comment (treshugart) [inline test/lib/create.js:1]: Boy scout: convenience since most elements we create are divs.

File: test/unit/dom/DocumentFragment.js [hunk 4]
```diff
@@ -1,23 +1,59 @@
 /* eslint-env jasmine, mocha */
 
+import create from '../../lib/create';
+
 describe('DocumentFragment', () => {
   it('should report the correct parent node for nested nodes', () => {
     const frag = document.createDocumentFragment();
-    const elem = document.createElement('div');
+    const elem = create();
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:8]: Boy scout: use test helper.

File: test/unit/dom/DocumentFragment.js [hunk 5]
```diff
@@ -1,23 +1,59 @@
...
     frag.appendChild(elem);
     expect(elem.parentNode).to.equal(frag);
   });
 
   it('should remove child elements when appending a document fragment', () => {
-    const div1 = document.createElement('div');
-    const div2 = document.createElement('div');
+    const div1 = create();
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:14]: Boy scout: use test helper.

File: test/unit/dom/DocumentFragment.js [hunk 6]
```diff
@@ -1,23 +1,59 @@
...
+    const div2 = create();
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:15]: Boy scout: use test helper.

File: test/unit/dom/DocumentFragment.js [hunk 7]
```diff
@@ -1,23 +1,59 @@
...
 
     const frag = document.createDocumentFragment();
     frag.appendChild(div1);
     frag.appendChild(div2);
 
-    const elem = document.createElement('div');
+    const elem = create();
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:21]: Boy scout: use test helper.

File: test/unit/dom/DocumentFragment.js [hunk 8]
```diff
@@ -1,23 +1,59 @@
...
     elem.appendChild(frag);
     expect(frag.childNodes.length).to.equal(0);
   });
+
+  it('should correctly report the host node of children that are reparented', () => {
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:26]: This is the reproducing test. I used 3 nodes instead of just one to ensure no node is left behind.

File: test/unit/dom/DocumentFragment.js [hunk 9]
```diff
@@ -1,23 +1,59 @@
...
+    // We ensure we're reporting the correct parent.
+    expect(ch1.parentNode).to.equal(target);
+    expect(ch2.parentNode).to.equal(target);
+    expect(ch3.parentNode).to.equal(target);
+
+    // It should also not error when removed. This is how the original problem
+    // presented itself. Theoretically this is ensured by checking the
+    // parentNode above, but it's probably good to have a sanity check here to
+    // ensure it's cleaned up.
+    ch1.parentNode.removeChild(ch1);
```
Comment (treshugart) [inline test/unit/dom/DocumentFragment.js:52]: This wasn't absolutely necessary, but it ensures the way this issue was uncovered is addressed properly.

File: yarn.lock [hunk 10]
```diff
@@ -132,14 +132,14 @@ ansi-escapes@^1.1.0:
   version "1.4.0"
   resolved "https://registry.yarnpkg.com/ansi-escapes/-/ansi-escapes-1.4.0.tgz#d3a8a83b319aa67793662b13e761c7911422306e"
 
-ansi-regex@*, ansi-regex@^2.0.0:
```
Comment (treshugart) [inline yarn.lock:135]: This whole file is just a side-effect of doing `yarn install`.

**Comment by madgnome** [comment]
Works where it was failing before!

**Review by adevnadia — APPROVED** [review]
