### PR TITLE
Fix tests in webkit.

### LINKED ISSUE #48: Tests break in Safari because code is assuming childNodes is an array.
In all browsers but Safari, it is because we polyfill childNodes at the prototype level. In Safari, however, we must polyfill `childNodes` selectively and it may not yet be an array so we must assume it's not.

### PR DESCRIPTION
**Pull request by treshugart**
Fixes #48.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -223,9 +225,9 @@ function registerNode (host, node, insertBefore, func) {
     }
 
     if (index > -1) {
-      host.childNodes.splice(index + eachIndex, 0, eachNode);
+      arrProto.splice.call(host.childNodes, index + eachIndex, 0, eachNode);
```
Comment (treshugart) [inline src/index.js:228]: The only issue with doing this is possible performance problems as we don't need to do this in any browser but Safari and only if `childNodes` isn't yet an array.

**Comment by jpnelson** [comment]
lgtm

**Comment by adevnadia** [comment]
lgtm
