### PR TITLE
#20 fix

### LINKED ISSUE #20: assignedSlot should be null for slots that participate in a shadow root that is closed
Currently we always return the `assignedSlot` for a light DOM node regardless of it's ancestor shadow root's `mode`. We should respect [the spec](http://w3c.github.io/webcomponents/spec/shadow/#attributes-2) here.

### PR DESCRIPTION
**Pull request by adevnadia**
#20 assignedSlot should be null for slots that participate in a shadow root that is closed

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -485,7 +489,7 @@ const members = {
   },
   assignedSlot: {
     get () {
-      return nodeToSlotMap.get(this) || null;
+      return (nodeToSlotMap.get(this) && hostToModeMap.get(rootToHostMap.get(slotToRootMap.get(nodeToSlotMap.get(this)))) === 'open') ? nodeToSlotMap.get(this) : null;
```
Comment (treshugart) [inline src/index.js]: Can I suggest this be broken down into `const`s to help make this more readable?

File: src/index.js [hunk 2]
```diff
@@ -370,6 +373,7 @@ function removeNodeFromRoot (root, node) {
 function removeSlotFromRoot (root, node) {
   node.assignedNodes().forEach(slotNodeFromSlot);
   delete rootToSlotMap.get(root)[getSlotNameFromSlot(node)];
+  delete slotToRootMap.get(node);
```
Comment (treshugart) [inline src/index.js]: This won't work as you're not deleting a key. You can call `slotToRootMap.delete(node)`, though.

**Comment by treshugart** [comment]
lgtm pending fixes

File: src/index.js (hunk 1 above)
Comment (joscha) [inline src/index.js]: I am not sure how expensive the lookups are - potentially splitting it into `const` means that the second half of `&&` is always evaluated unless we do early returns instead.

File: src/index.js [hunk 3]
```diff
@@ -332,6 +333,8 @@ function addSlotToRoot (root, slot) {
   }
 
   rootToSlotMap.get(root)[slotName] = slot;
+  !slotToRootMap.has(slot) && slotToRootMap.set(slot, root);
```
Comment (joscha) [inline src/index.js:336]: short guards should be discouraged by our eslint rules?!

Comment (treshugart) [inline src/index.js:336]: Not sure. I don't have a strong opinion about this.

Comment (adevnadia) [inline src/index.js:336]: Why would they? What is wrong with it?
They are not now, as far as I can see.

Comment (joscha) [inline src/index.js:336]: Because they are easily overread - they are definitely flagged in AUI. All good if they are not in named-slots

Comment (treshugart) [inline src/index.js:336]: We should probably try to keep the coding styles similar, even if they're separate projects. We maintain both and the less cognitive overhead in doing so, the better.

Comment (nadiam84) [inline src/index.js]: I disagree about short guards, but agree with the idea of similar coding styles.
@treshugart how do you feel about adding atlassian eslint rules to skate build?

Comment (adevnadia) [inline src/index.js:336]: I checked, with aui-style eslint there is no mistake in this part of code

Comment (joscha) [inline src/index.js:336]: I think it might not be migrated and still in JSCS - don't worry about it, it is not a blocker for this PR I think, I was just surprised to see it.

Comment (adevnadia) [inline src/index.js:336]: I assume this means that this is LGTM from you? :)

Comment (joscha) [inline src/index.js:336]: Haha, yes, go ahead!

**Comment by jpnelson** [comment]
lgtm
