### PR TITLE
fix: remove Array.from

### LINKED ISSUE #97: Transpiler compiles down to Array.from which is not available in all browsers
At https://github.com/skatejs/named-slots/blob/master/src/index.js#L396 the array spread operator is used. This transpiles to `Array.from()` which isn't available in all browsers. This should be changed so it doesn't need a polyfill.

### PR DESCRIPTION
**Pull request by joscha**
closes #97

### CODE REVIEW

File: src/util/nodelist-to-array.js [hunk 1]
```diff
@@ -0,0 +1 @@
+export default (nodeList) => Array.prototype.slice(nodeList);
```
Comment (treshugart) [inline src/util/nodelist-to-array.js]: `Array.prototype.slice.call(nodeList)`?

Also nit: parenthesis aren't needed in single argument arrow functions.

Comment (treshugart) [inline src/util/nodelist-to-array.js]: This works for more than node lists, so I wonder if it's worth reflecting that in the name?

**Comment by treshugart** [comment]
lgtm pending comments
