### PR TITLE
Fix 38 clone node

### LINKED ISSUE #38: Not cloning nodes in createElements means that polyfill is incomplete
In particular, the problem is:

```
div.innerHTML = '<a/> <b/> <c/>';
```

It counts incorrectly in createElement because it doesn't clone nodes, the copying procedure mutates the original.

### PR DESCRIPTION
**Pull request by jpnelson**
Fixes #38

### CODE REVIEW

File: test/unit.js [hunk 1]
```diff
@@ -227,6 +227,14 @@ describe('skatejs-named-slots', function () {
       expect(slot.getAssignedNodes().length).to.equal(1);
     });
 
+    it('innerHTML (with whitespace text nodes)', function () {
+      expect(host.innerHTML).to.equal('');
+      host.innerHTML = '<div> <button></button> </div>';
+      expect(host.innerHTML).to.equal('<div> <button></button> </div>');
+      expect(host.childNodes.length).to.equal(1);
```
Comment (treshugart) [inline test/unit.js]: Shouldn't this be 3?

**Comment by treshugart** [comment]
lgtm

**Comment by adevnadia** [comment]
lgtm
