### PR TITLE
fix(v1): patch DocumentFragment prototype

### LINKED ISSUE #135: DocumentFragment prototype is not polyfilled
This means that appending nodes to a document fragment does not do necessary house keeping to the WeakMap caches (e.g. updating `parentNode`).

Investigation: http://www.webpackbin.com/4y0m8cs1M

### PR DESCRIPTION
**Pull request by bradleyayers**
fixes #135

### CODE REVIEW

File: test/unit/dom/appendChild.js [hunk 1]
```diff
@@ -221,4 +221,31 @@ describe('dom: appendChild', () => {
   runTests('slot');
   runTests('host');
   runTests('root');
+
+  describe('fragment:', () => {
```
Comment (adevnadia) [inline test/unit/dom/appendChild.js]: Would it be possible (and worth the effort?) instead of manually creating this test just include DocumentFragment inside all the other tests? It seems like it's a matter of changing `switch/case` function and adding additional `runTests('documentFragment');`.

Comment (bradleyayers) [reply test/unit/dom/appendChild.js]: That was my original approach, and the vast majority of the tests failed, so I switched to breaking it out to be specific to fragment.

Fragment is fundamentally different from the others, so I was comfortable with this deviation.
